adds check connection functionality, adds git-continue, updates some custom git commands, switches back to oh my zsh nvm plugin

diff --git a/git/bin/git-rename b/git/bin/git-rename
--- a/git/bin/git-rename
+++ b/git/bin/git-rename
@@ -1,5 +1,7 @@
 #!/bin/zsh
 
+#? Reference https://linuxize.com/post/how-to-rename-local-and-remote-git-branch/
+
 autoload colors; colors
 
 usage() {
@@ -27,7 +29,6 @@ shift $((OPTIND -1))
 
 [[ $# -eq 0 ]] && echo "(g|git) rename requires 1 or 2 arguments" usage && exit 1
 
-echo $@
 git branch -m $@
 
 local new_branch old_branch
@@ -40,6 +41,6 @@ else
 fi
 
 if [[ $(git show-branch remotes/origin/$old_branch &> /dev/null) ]]; then
-  [[ $(git push origin :$old_branch $new_branch) ]] || echo "Attempt to rename remote branch failed"
   git push origin -u $new_branch
+  [[ $(git push origin --delete $old_branch) ]] || echo "Attempt to rename remote branch failed"
 fi
