updates git-co - when checking a new branch based on master, checks if branch exists and if so, offers to merge latest changes from master - when checking out a new branch, checks if branch exists and if so will just checkout the existing branch - changes exits for returns
updates git-merge-master
- adds ability to rebase instead of merge

updates git-up
- adds option to turn off check for changes to dependencies and node version

updates to aliases
- adds g aliased to `git`
- adds shortcut for `yarn flow` and a combo shortcut for `yarn test && yarn flow`

updates to functions
- removes `g()` function to just use git aliases for cloning/cd command

updates to gitconfig
- adds `cl` for cloning and `cd` into new repo directory
- adds `col` for checkout out last branch/`corl` for a static list of recent branches
- adds `mmr` to trigger merge-master with rebase
- adds `rc` to continue with rebase or open git merge tool if conflicted

diff --git a/git/bin/git-up b/git/bin/git-up
--- a/git/bin/git-up
+++ b/git/bin/git-up
@@ -2,7 +2,27 @@
 
 autoload colors; colors
 
+local check=true
+
+while getopts "C" opt; do
+  case $opt in
+    C)
+      check=false
+      ;;
+    \?)
+      echo "Invalid option: -$OPTARG"
+      return 1
+      ;;
+    :)
+      echo "Option -$OPTARG requires an argument"
+      return 1
+      ;;
+  esac
+done
+shift "$((OPTIND-1))"
+
 local branch=$(git for-each-ref --format='%(upstream:short)' "$(git symbolic-ref -q HEAD)")
+[[ -z $branch ]] && echo "Current branch (`git rev-parse --abbrev-ref HEAD`) has no upstream" && exit 1
 local pkg=false
 local nvm=false
 echo "Merging from $branch"
@@ -10,23 +30,29 @@ echo
 
 git fetch --prune origin
 
-# check for yarn.lock and set pkg
+# check for yarn.lock and set dep
 # check for .nvmrc and set nvm
-[[ $(git diff --name-only "$branch" | grep "yarn.lock") ]] && pkg=true
-[[ $(git diff --name-only "$branch" | grep ".nvmrc") ]] && nvm=true
+local gdiff=`git diff --name-only "$branch"`
+if [[ $check = true ]]; then
+  [[ $(grep "yarn.lock" <<< $gdiff) ]] && dep=true
+  [[ $(grep ".nvmrc" <<< $gdiff) ]] && nvm=true
+fi
 
 git merge "$branch"
-echo
 
-if $pkg; then
-    echo "yarn.lock has been updated"
-    echo
-    bounce
-fi
+function update_dep() {
+  echo
+  echo "Changes detected in yarn.lock"
+  echo
+  bounce
+}
 
-if $nvm; then
-  echo ".nvmrc has changed"
-  echo "Running $fg[blue]nvm use$reset_color"
+function update_node() {
+  echo
+  echo "Change detected in .nvmrc"
   echo
   nvm use
-fi
+}
+
+[[ $dep = true ]] && update_dep
+[[ $nvm = true ]] && update_node
