restructures setup files

diff --git a/git/bin/git-co b/git/bin/git-co
--- a/git/bin/git-co
+++ b/git/bin/git-co
@@ -41,6 +41,8 @@ unstash() {
   [[ $stashed == 1 ]] && echo && git stash pop
 }
 
+local default_branch=$(git remote show origin | sed -n '/HEAD branch/s/.*: //p')
+
 while getopts ":B:b:lmr:" opt; do
   case ${opt} in
     B) # Checkout new branch based on latest master
@@ -52,8 +54,8 @@ while getopts ":B:b:lmr:" opt; do
       fi
 
       stash
-      git checkout master
-      git up || echo "\n$fg[yellow]Pull failed. Don't forget to rebase master$reset_color\n"
+      git checkout $default_branch
+      git up || echo "\n$fg[yellow]Pull failed. Don't forget to rebase $default_branch$reset_color\n"
       git checkout -b $OPTARG
       ask_unstash
       return 0
@@ -71,7 +73,7 @@ while getopts ":B:b:lmr:" opt; do
       ;;
     m) # Checkout master branch
       stash
-      git checkout master
+      git checkout $default_branch
       git check-stash
       return 0
       ;;
